#import "./collectionFragment.gql"

query collections($filter: CollectionFilterQuery) @api(name: game) {
  collections(filter: $filter) {
    items {
      ...CollectionFields
    }
    total
    page
    limit
  }
}
