#import "./collectionFragment.gql"

mutation updateCollectionSocialLinks($id: ID!, $input: [SocialLinkInput!]!) @api(name: game) {
  updateCollectionSocialLinks(id: $id, input: $input) {
    success
    collection {
      ...CollectionFields
    }
  }
}
