mutation createNft($input: NftInput!) @api(name: project) {
    createNft(input: $input) {
        nft {
            collection_id
            project_id
            name
            parent_id
            properties
            custom_props
            config
            formats
            description
            price
            supply
            nft_type
            asset_url
        }
        success
        message
    }
}