mutation insertNfts($input: [InsertNftsInput!]!, $project_id: ID!, $collection_id: ID!) @api(name: project) {
    insertNfts(input: $input, project_id: $project_id, collection_id: $collection_id) {
        success
        message
        nfts {
            id
            supply
            asset_url
            name
        }
        total_imported
        not_imported {
            name
            parent_id
            properties
            custom_props
            description
            price
            supply
            asset_url
            message
            error
        }
    }
}