mutation updateAchievement($id: ID!, $input: AchievementInput!) @api(name: game) {
  updateAchievement(id: $id, input: $input) {
    id
    name
    game_id
    account_id
    created_on
    modified_on
    created_by
    modified_by
    description
    order
    media
  }
}
