#import "./gameFragment.gql"

mutation updateGameSocialLinks($id: ID!, $input: [SocialLinkInput!]!) @api(name: game) {
  updateGameSocialLinks(id: $id, input: $input) {
    success
    game {
      ...GameFields
    }
  }
}
