mutation changePassword($currentPassword: String!, $password: String!) @api(name:project)  {
  changePassword(currentPassword: $currentPassword, password: $password) {
      message
      success
  }
}
