mutation batchDeleteAssets($ids: [String]!, $collection_id: ID, $project_id: ID)
@api(name: project) {
  batchDeleteAssets(ids: $ids, collection_id: $collection_id, project_id: $project_id) {
    success
    message
  }
}
