mutation createAsset($input: AssetInput!) @api(name: game) {
  createAsset(input: $input) {
    asset {
      id
      collection_id
      game_id
      name
      parent_id
      properties
      attributes
      custom_props
      config
      formats
      description
      price
      supply
      asset_type
      asset_url
      medias
      token_id
    }
    success
    message
  }
}
