mutation updateAssetMedia($id: ID!, $input: [MediaInput!]!) @api(name: project) {
  updateAssetMedia(id: $id, input: $input) {
    success
    asset {
      id
      name
      project_id
      account_id
      created_on
      modified_on
      created_by
      modified_by
      parent_id
      properties
      custom_props
      config
      formats
      description
      status
      price
      supply
      mintedAmount
      asset_type
      asset_url
      collection_id
      medias
    }
  }
}
