mutation createGame($game: GameInput!) @api(name: game) {
  createGame(game: $game) {
    id
    game_name
    annual_travel_distance
    holding_period
    pool_vehicle
    game_name
    location_postcode
  }
}
