mutation createProject($game: ProjectInput!) @api(name: game) {
  createProject(game: $game) {
    id
    project_name
    annual_travel_distance
    holding_period
    pool_vehicle
    project_name
    location_postcode
  }
}
