declare module '@l3-lib/ui-core/dist/Button'
declare module '@l3-lib/ui-core/dist/TextField'
declare module '@l3-lib/ui-core/dist/Dropdown'
declare module '@l3-lib/ui-core/dist/Heading'
declare module '@l3-lib/ui-core/dist/Search'
