mutation createMessage($input: input!) @api(name: ai) {
  createMessage: publish(input: $input)
    @rest(
      type: "CreateMessageV2"
      path: "/ask/v2"
      method: "POST"
      bodyKey: "input"
      endpoint: "ai"
    )
}
