query transactions($filter: TransactionFilterQuery) @api(name: game) {
  transactions(filter: $filter) {
    items {
      id
      contract_address
      from
      from_player {
        id
        unique_id
        name
        username
        avatar
      }
      to
      to_player {
        id
        unique_id
        name
        username
        avatar
      }
      blockchain
      chain_name
      transaction_hash
      events
      method
      created_on
      type
      transaction_assets {
        id
        amount
        asset {
          id
          token_id
          name
          asset_type
          medias
        }
      }
    }
  }
}
