query transactionsByPlayer($player_id: ID!) @api(name: project) {
  transactionsByPlayer(player_id: $player_id) {
    items {
      id
      from
      to
      contract_address
      blockchain
      chain_name
      chain_id
      environment
      transaction_hash
      method
      events
      status
      project_id
      collection_id
      deleted
      created_on
      modified_on
      created_by
      modified_by
    }
  }
}
