#import "./playerAssetFragment.gql"

query playerAssetsByCollections($filter: PlayerAssetsByCollectionsInput) @api(name: game) {
  playerAssetsByCollections(filter: $filter) {
    items {
      name
      categories
      player_assets {
        ...PlayerAssetFragment
      }
    }
    total_player_assets
  }
}
