#import "./playerAssetFragment.gql"

query playerAssets($filter: PlayerAssetFilterQuery) @api(name: game) {
  playerAssets(filter: $filter) {
    items {
      ...PlayerAssetFragment
    }
    total
    page
    limit
  }
}
