mutation createProperty($input: PropertyInput!) @api(name: game) {
  createProperty(input: $input) {
    property {
      id
      name
      value
      game_id
      account_id
      created_on
      modified_on
      created_by
      modified_by
      description
      media
      property_type
      collection_id
      order
    }
    success
    message
  }
}
