mutation forgotPassword($body: JSON!) {
  forgotPassword: publish(body: $body) @rest(
      type: "Post"
      path: "/auth/forgot-password"
      method: "POST"
      bodyKey: "body",
      endpoint: "project"
    ) {
      message
      success
  }
}
