query contracts($filter: ContractFilterQuery) @api(name: project) {
  contracts(filter: $filter) {
    items {
      id
      name
      contract_type
      blockchain
      chain_name
      chain_id
      environment
      template
      config
      note
      status
      source_code {
        file_name
        code
      }
      abi
      constructor_args
      deployer_address
      contract_address
      transaction_hash
      collection_id
    }
    total
    page
    limit
  }
}
