query contractByCollectionId($id: ID!) @api(name: project) {
  contractByCollectionId(id: $id) {
    id
    name
    contract_type
    blockchain
    chain_name
    chain_id
    environment
    template
    config
    note
    status
    source_code {
      file_name
      code
    }
    abi
    bytecode
    constructor_args
    deployer_address
    contract_address
    transaction_hash
  }
}
