#import "./contractFragment.gql"

query contracts($filter: ContractFilterQuery) @api(name: project) {
  contracts(filter: $filter) {
    items {
      ...ContractFragment
    }
    total
    page
    limit
  }
}
