fragment ContractFragment on Contract {
  id
  name
  contract_type
  blockchain
  chain_name
  chain_id
  environment
  template
  config
  note
  status
  abi
  source_code {
    file_name
    code
  }
  constructor_args
  constructor_config
  deployer_address
  contract_address
  transaction_hash
  collection_id
  game_id
}
