#import "./contractFragment.gql"

mutation createContract($input: ContractInput!) @api(name: game) {
  createContract(input: $input) {
    contract {
      ...ContractFragment
    }
    success
    message
  }
}
