mutation deployContract($id: ID!) @api(name: game) {
  deployContract(id: $id) {
    id
    abi
    bytecode
    constructor_args
    transaction_hash
    source_code {
      file_name
      code
    }
  }
}
