#import "./contractFragment.gql"

mutation updateContract($id: ID!, $input: UpdateContractInput!) @api(name: project) {
  updateContract(id: $id, input: $input) {
    contract {
      ...ContractFragment
    }
    success
    message
  }
}
