#import "../collection/collectionFragment.gql"
#import "./contractFragment.gql"

mutation updateMetadata($collection_id: ID!) @api(name: game) {
  updateMetadata(collection_id: $collection_id) {
    collection {
      ...CollectionFields
    }
    contract {
      ...ContractFragment
    }
    transaction_hash
  }
}
