query achievements($filter: AchievementFilterQuery) @api(name: game) {
  achievements(filter: $filter) {
    items {
      id
      name
      game_id
      account_id
      created_on
      modified_on
      created_by
      modified_by
      parent_id
      custom_props
      config
      description
      status
      asset_url
      value
      order
      media
      main_media
    }
    total
    page
    limit
  }
}
