#import "./projectFragment.gql"

mutation createProject($input: ProjectInput!)  @api(name: project) {
    createProject(input: $input) {
        project {
            ...ProjectFields
        }
        success
        message
    }
}