#import "./projectFragment.gql"

mutation createProject($input: ProjectInput!) @api(name: game) {
  createProject(input: $input) {
    game {
      ...ProjectFields
    }
    success
    message
  }
}
