#import "./projectFragment.gql"

query projects($filter: ListFilterQuery) @api(name: project) {
    projects(filter: $filter) {
        items {
            ...ProjectFields
        }
        total
        page
        limit
    }
}
