#import "./gameFragment.gql"

mutation setDefaultGameMedia($game_id: ID!, $media_id: ID!) @api(name: game) {
  setDefaultGameMedia(game_id: $game_id, media_id: $media_id) {
    success
    game {
      ...GameFields
    }
  }
}
