#import "./gameFragment.gql"

mutation updateGameMedias($id: ID!, $input: [MediaInput!]!) @api(name: game) {
  updateGameMedias(id: $id, input: $input) {
    success
    game {
      ...GameFields
    }
  }
}
