#import "./projectFragment.gql"

mutation updateProject($id: ID!, $input: ProjectInput!) @api(name: game) {
  updateProject(id: $id, input: $input) {
    success
    game {
      ...ProjectFields
    }
  }
}
