#import "./projectFragment.gql"

mutation updateProjectSocialLinks($id: ID!, $input: [SocialLinkInput!]!) @api(name: game) {
  updateProjectSocialLinks(id: $id, input: $input) {
    success
    game {
      ...ProjectFields
    }
  }
}
