name: "02-S3Bucket"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    uses: l3vels/l3-ui/.github/workflows/aws_tf_plan.yml@main
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Uat
    uses: l3vels/l3-ui/.github/workflows/aws_tf_apply.yml@main
    with:
      path: S3Bucket
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}