name: "Deploy to AWS CloudFront"
on:
  push:
    branches:
      - main

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    uses: l3vels/l3-ui/.github/workflows/aws_tf_plan.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: l3vels/l3-ui/.github/workflows/aws_tf_apply.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
  Sync_S3_Dev:
    needs: Deploy_Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup yarn
        run: npm install -g yarn

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
    
      - name: Install project dependencies
        run: yarn install

      - name: Build Project
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Sync files to S3
        env:
          S3_DOMAIN_NAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: aws s3 sync build/ s3://dashboard-dev.$S3_DOMAIN_NAME --delete

     