name: "Cloudfront"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    uses: l3vels/l3-ui/.github/workflows/aws_tf_plan.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: l3vels/l3-ui/.github/workflows/aws_tf_apply.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}