name: "Cloudfront"
on:
  push:
    branches:
      - main

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/main'
    uses: l3vels/l3-ui/.github/workflows/aws_tf_plan.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: l3vels/l3-ui/.github/workflows/aws_tf_apply.yml@main
    with:
      path: terraform
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
  Sync_S3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
    
      - name: Install Yarn dependencies
        run: yarn install
        
      - name: Build Project
        run: |
          Yarn install
          Yarn run build
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Sync files to S3
        run: aws s3 sync build/ s3://dashboard-dev.l3vels.xyz --delete

     